verification_config:
    secret: 00000000-0000-000000000-000000000000
    query_name: "echo_challenge"
    cookie_name: "echo_challenge"
    header_name: "Echo-Challenge"
default_status_code: 500
server_configs:
    - host: 0.0.0.0
      port: 80
      enable: true
      certificate_path: ""
      private_key_path: ""
    - host: 0.0.0.0
      port: 443
      enable: false
      certificate_path: assets/certificates/www.example.com/fullchain.pem
      private_key_path: assets/certificates/www.example.com/privkey.pem